name: Deploy to neocities

# run on changes to main branch or when manually triggered
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: 2
  node_version: 20

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
      - run: npm i
      - run: npm run build
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: website-artifacts
          path: _dist

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: website-artifacts
          path: _dist
      - name: List contents of the working directory
        run: ls -al
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: _dist
